# Generated by Django 5.2.8 on 2025-12-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('concept', models.CharField(max_length=200)),
                ('reference_number', models.CharField(max_length=50)),
                ('proof_image', models.ImageField(upload_to='payments/')),
                ('status', models.CharField(choices=[('PENDING', 'En Revisión'), ('VERIFIED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_id', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academic.student')),
            ],
        ),
    ]
