# Generated by Django 5.2.8 on 2025-12-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visible_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
