# Generated by Django 5.2.8 on 2025-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
